<?php
/**
 * Responsive candidates for theme-hosted content images.
 *
 * WordPress adds srcset, sizes, and intrinsic dimensions only to images it can
 * resolve to an attachment — wp_image_add_srcset_and_sizes() and
 * wp_img_tag_add_width_and_height_attr() both start from an attachment ID. The
 * Job Placement Digest's event photograph is a theme asset tracked in git, not
 * an upload, so core leaves it alone and every viewport downloads the full
 * 1448w frame.
 *
 * The obvious fix — writing srcset into the block markup — is not available
 * here. core/image has no srcset or sizes attribute, so hand-authored ones
 * cannot be regenerated by the block's save function and the page fails block
 * validation the next time it is opened in the editor. Raw HTML would dodge
 * that, but the Digest body is required to stay natively editable (see the
 * guard in scripts/verify-job-placement-digest-source.js). So the body keeps a
 * plain wp:image block an editor can still edit, and the delivery detail is
 * added here at render time.
 *
 * The About showcase's two evidence screenshots arrive the same way and for the
 * same reason: they are theme assets, the body is under the About page-content
 * contract, and a card thumbnail has no business shipping its full frame.
 *
 * @package HPerkins_Tokens
 */

defined( 'ABSPATH' ) || exit;

/**
 * Theme-hosted content images that ship a smaller candidate.
 *
 * Keyed by the file name as it appears in the rendered src, which is how the
 * filter below recognises the image without depending on the authored path.
 *
 * Candidate width and sizes are both derived from the layout, not from a
 * measured render. The Digest figure's negative margins cancel --hp-plate-pad
 * exactly, so the figure is as wide as the alignwide plate itself:
 * calc(100vw - 4rem) under the 2rem root padding, capped at the 72rem wideSize
 * once the viewport clears 72rem + 4rem = 1216px. A phone therefore lays it out
 * near 326px and takes the 768w candidate at 2x — the same candidate width the
 * ring cards already use. The byte budgets live with the rest of the artwork in
 * scripts/verify-performance-assets.js.
 *
 * @return array<string, array<string, string|int>> Candidate descriptors.
 */
function hperkins_tokens_content_image_candidates() {
	// Both showcase screenshots sit in the same box, so they share one sizes
	// string. The cards are two to a row at every width, so a card is half the
	// content column less the grid gap. Backdrop figures cover the whole card,
	// outside the filter rail: up to 504px on desktop. Half the viewport below
	// 1024px safely covers the fluid gutters; 32rem caps the wide layout.
	$showcase_card_sizes = '(max-width: 1023px) 50vw, 32rem';

	return array(
		'wcus-2026-phoenix.webp'                  => array(
			'full'        => 'assets/img/imagery/wcus-2026-phoenix.webp',
			'small'       => 'assets/img/imagery/wcus-2026-phoenix-768.webp',
			'small_width' => 768,
			'width'       => 1448,
			'height'      => 1086,
			'sizes'       => '(max-width: 1216px) calc(100vw - 4rem), 72rem',
		),
		'flavor-agent-activity-log.webp'          => array(
			'full'        => 'assets/screenshots/flavor-agent-activity-log.webp',
			'small'       => 'assets/screenshots/flavor-agent-activity-log-640.webp',
			'small_width' => 640,
			'width'       => 1024,
			'height'      => 953,
			'sizes'       => $showcase_card_sizes,
		),
		'ai-provider-codex-runtime-settings.webp' => array(
			'full'        => 'assets/screenshots/ai-provider-codex-runtime-settings.webp',
			'small'       => 'assets/screenshots/ai-provider-codex-runtime-settings-640.webp',
			'small_width' => 640,
			'width'       => 1024,
			'height'      => 540,
			'sizes'       => $showcase_card_sizes,
		),
		// The theme's own card shows the mascot rather than a screenshot. It is
		// contained inside the same plate, so it shares the sizes string; its
		// full frame is the master's native width, since nothing above the card
		// ever asks for more.
		'wapuu-hero.webp'                        => array(
			'full'        => 'assets/wapuu/wapuu-hero.webp',
			'small'       => 'assets/wapuu/wapuu-hero-448.webp',
			'small_width' => 448,
			'width'       => 832,
			'height'      => 966,
			'sizes'       => $showcase_card_sizes,
		),
	);
}

/**
 * Adds responsive candidates and intrinsic dimensions to theme-hosted images.
 *
 * Runs on wp_content_img_tag, which fires once per <img> inside
 * wp_filter_content_tags(). Core has already made its loading decision by then,
 * so this deliberately does not touch loading or fetchpriority: the photograph
 * is the first content image on the route, which is exactly the case
 * wp_get_loading_optimization_attributes() already keeps eager.
 *
 * @param string $filtered_image The full img tag.
 * @return string The img tag, with candidates added when one is registered.
 */
function hperkins_tokens_add_content_image_candidates( $filtered_image ) {
	foreach ( hperkins_tokens_content_image_candidates() as $file_name => $candidate ) {
		if ( false === strpos( $filtered_image, $file_name ) ) {
			continue;
		}

		// Never fight an srcset that is already present: the same photograph
		// added through the media library would arrive carrying core's own.
		if ( false !== strpos( $filtered_image, 'srcset=' ) ) {
			return $filtered_image;
		}

		$full  = esc_url( hperkins_tokens_asset_url( $candidate['full'] ) );
		$small = esc_url( hperkins_tokens_asset_url( $candidate['small'] ) );

		// Point the fallback src at the same cache-busted URL the srcset names,
		// so one file never occupies two cache entries. Matched first and
		// swapped with str_replace(), because a preg_replace() replacement
		// string would reinterpret any $ or \ that survives esc_url().
		if ( preg_match( '#\ssrc="[^"]*' . preg_quote( $file_name, '#' ) . '"#', $filtered_image, $matches ) ) {
			$filtered_image = str_replace( $matches[0], ' src="' . $full . '"', $filtered_image );
		}

		$attributes = sprintf(
			'srcset="%1$s %2$dw, %3$s %4$dw" sizes="%5$s" width="%4$d" height="%6$d" ',
			$small,
			(int) $candidate['small_width'],
			$full,
			(int) $candidate['width'],
			esc_attr( $candidate['sizes'] ),
			(int) $candidate['height']
		);

		return str_replace( '<img ', '<img ' . $attributes, $filtered_image );
	}

	return $filtered_image;
}

add_filter( 'wp_content_img_tag', 'hperkins_tokens_add_content_image_candidates' );
