<?php
/**
 * Responsive candidates for theme-hosted content images.
 *
 * WordPress adds srcset, sizes, and intrinsic dimensions only to images it can
 * resolve to an attachment — wp_image_add_srcset_and_sizes() and
 * wp_img_tag_add_width_and_height_attr() both start from an attachment ID. The
 * Job Placement Digest's event photograph is a theme asset tracked in git, not
 * an upload, so core leaves it alone and every viewport downloads the full
 * 1448w frame.
 *
 * The obvious fix — writing srcset into the block markup — is not available
 * here. core/image has no srcset or sizes attribute, so hand-authored ones
 * cannot be regenerated by the block's save function and the page fails block
 * validation the next time it is opened in the editor. Raw HTML would dodge
 * that, but the Digest body is required to stay natively editable (see the
 * guard in scripts/verify-job-placement-digest-source.js). So the body keeps a
 * plain wp:image block an editor can still edit, and the delivery detail is
 * added here at render time.
 *
 * The About showcase's two evidence screenshots arrive the same way and for the
 * same reason: they are theme assets, the body is under the About page-content
 * contract, and a card thumbnail has no business shipping its full frame.
 *
 * @package HPerkins_Tokens
 */

defined( 'ABSPATH' ) || exit;

/**
 * Theme-hosted content images that ship a smaller candidate.
 *
 * Keyed by the file name as it appears in the rendered src, which is how the
 * filter below recognises the image without depending on the authored path.
 *
 * Candidate width and sizes are both derived from the layout, not from a
 * measured render. The Digest figure's negative margins cancel --hp-plate-pad
 * exactly, so the figure is as wide as the alignwide plate itself:
 * calc(100vw - 4rem) under the 2rem root padding, capped at the 72rem wideSize
 * once the viewport clears 72rem + 4rem = 1216px. A phone therefore lays it out
 * near 326px and takes the 768w candidate at 2x — the same candidate width the
 * ring cards already use. The byte budgets live with the rest of the artwork in
 * scripts/verify-performance-assets.js.
 *
 * @return array<string, array<string, string|int>> Candidate descriptors.
 */
function hperkins_tokens_content_image_candidates() {
	// Narrow work records use one column. Their optional images remain deferred
	// while hidden by the text-led phone layout; larger cards keep their backdrop.
	$showcase_card_sizes = '(max-width: 600px) calc(100vw - 2rem), (max-width: 1023px) 50vw, 32rem';

	return array(
		'henry-perkins.png'                     => array(
			'full'        => 'assets/img/henry-perkins-240.webp',
			'small'       => 'assets/img/henry-perkins-120.webp',
			'small_width' => 120,
			'width'       => 240,
			'height'      => 240,
			'sizes'       => '80px',
		),
		'tableu.png'                            => array(
			'full'        => 'assets/img/marks/tableu-634.webp',
			'small'       => 'assets/img/marks/tableu-320.webp',
			'small_width' => 320,
			'width'       => 634,
			'height'      => 845,
			'sizes'       => $showcase_card_sizes,
		),
		'wcus-2026-phoenix.webp'                  => array(
			'full'        => 'assets/img/imagery/wcus-2026-phoenix.webp',
			'small'       => 'assets/img/imagery/wcus-2026-phoenix-768.webp',
			'small_width' => 768,
			'width'       => 1448,
			'height'      => 1086,
			'sizes'       => '(max-width: 1216px) calc(100vw - 4rem), 72rem',
		),
		'flavor-agent-activity-log.webp'          => array(
			'full'        => 'assets/screenshots/flavor-agent-activity-log.webp',
			'small'       => 'assets/screenshots/flavor-agent-activity-log-640.webp',
			'small_width' => 640,
			'width'       => 1024,
			'height'      => 953,
			'sizes'       => $showcase_card_sizes,
		),
		'ai-provider-codex-runtime-settings.webp' => array(
			'full'        => 'assets/screenshots/ai-provider-codex-runtime-settings.webp',
			'small'       => 'assets/screenshots/ai-provider-codex-runtime-settings-640.webp',
			'small_width' => 640,
			'width'       => 1024,
			'height'      => 540,
			'sizes'       => $showcase_card_sizes,
		),
		// The theme's own card shows the mascot rather than a screenshot. It is
		// contained inside the same plate, so it shares the sizes string; its
		// full frame is the master's native width, since nothing above the card
		// ever asks for more.
		'wapuu-hero.webp'                        => array(
			'full'        => 'assets/wapuu/wapuu-hero.webp',
			'small'       => 'assets/wapuu/wapuu-hero-448.webp',
			'small_width' => 448,
			'width'       => 832,
			'height'      => 966,
			'sizes'       => $showcase_card_sizes,
		),
	);
}

/**
 * Adds responsive candidates and intrinsic dimensions to theme-hosted images.
 *
 * Runs after core's loading pass. Only the About portrait and its four known
 * deep-page showcase assets get explicit priority; the Digest photograph and
 * every other route retain core's policy. The tag processor preserves upstream
 * attributes and avoids duplicate dimensions or regex-sensitive URL rewrites.
 *
 * @param string $filtered_image The full img tag.
 * @return string The img tag, with candidates added when one is registered.
 */
function hperkins_tokens_add_content_image_candidates( $filtered_image ) {
	$tag = new WP_HTML_Tag_Processor( $filtered_image );
	if ( ! $tag->next_tag( 'IMG' ) ) {
		return $filtered_image;
	}
	$src        = (string) $tag->get_attribute( 'src' );
	$image_path = (string) wp_parse_url( $src, PHP_URL_PATH );
	$file_name  = basename( $image_path );
	$candidates = hperkins_tokens_content_image_candidates();
	if ( ! isset( $candidates[ $file_name ] ) ) {
		return $filtered_image;
	}
	$is_portrait = 'henry-perkins.png' === $file_name;
	if ( $is_portrait && ! str_ends_with( $image_path, '/uploads/2026/06/henry-perkins.png' ) ) {
		return $filtered_image;
	}
	$candidate = $candidates[ $file_name ];
	if ( ! $tag->get_attribute( 'srcset' ) ) {
		$full  = hperkins_tokens_asset_url( $candidate['full'] );
		$small = hperkins_tokens_asset_url( $candidate['small'] );
		$tag->set_attribute( 'src', $full );
		$tag->set_attribute( 'srcset', sprintf( '%s %dw, %s %dw', $small, $candidate['small_width'], $full, $candidate['width'] ) );
		$tag->set_attribute( 'sizes', $candidate['sizes'] );
		$tag->set_attribute( 'width', $candidate['width'] );
		$tag->set_attribute( 'height', $candidate['height'] );
	}
	if ( is_page( 'about' ) && 'wcus-2026-phoenix.webp' !== $file_name ) {
		$tag->set_attribute( 'loading', $is_portrait ? 'eager' : 'lazy' );
		$tag->set_attribute( 'decoding', 'async' );
		if ( ! $is_portrait ) {
			$tag->remove_attribute( 'fetchpriority' );
		}
	}
	return $tag->get_updated_html();
}

add_filter( 'wp_content_img_tag', 'hperkins_tokens_add_content_image_candidates' );
